name: Build Project

on:
  push:
    branches:
     - main

jobs:
  build-windows:
    name: Create Windows build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Build
      - name: Build 
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: StandaloneWindows64.zip

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: WindowsStandalone64.zip
  
  build-webgl:
    name: Create WebGL build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildName: WebGL.zip

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: WebGL.zip
  
  build-android:
    name: Create Android build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          buildName: Android.zip

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Android.zip